### ISSUE TITLE
Package BuildRequires python3-mock

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [SUSE/SAPStartSrv-resourceAgent#34]
This package requires python3-mock to build, and the Python packaging team are currently working towards removing that package since the lowest version of Python currently shipped in Tumbleweed provides mocking ability via unittest.mock. I see you've already changed the test code to support importing that instead. I'd suggest removing the BuildRequires for Factory only, or if that is not possible, guarding it with suse_version < 1500.

**Comment by angelabriel** [comment]
This should be already solved in the current used spec file, if I'm not wrong. The lines 17 to 21 define a build condition 'test' for suse_version < 1500. And the lines 36 to 39 set the build require for python3-mock only, if build condition is 'with test'. So on tumbleweed the python3-mock should not be necessary any more for the build of SAPStartSrv.

**Comment by s-t-e-v-e-n-k** [comment]
The version of SAPStartSrv in Tumbleweed hasn't been updated for one year, so this bug still impacts Tumbleweed.

**Comment by angelabriel** [comment]
Looking at https://build.opensuse.org/package/view_file/openSUSE:Factory/sapstartsrv-resource-agents/sapstartsrv-resource-agents.spec?expand=1 it shows, that these changes are already available in tumbleweed.
But as it seems that this is not sufficient, I will remove the whole 'mock and test' part from the package with the next maintenance update of the package.
Is there a timeline till this change has to reach tumbleweed?

**Comment by s-t-e-v-e-n-k** [comment]
I'll investigate a little further, see if I can come up with a patch to fix Tumbleweed -- not as yet, I don't have a timeline

**Comment by s-t-e-v-e-n-k** [comment]
```
%if 0%{?suse_version} < 1500
%bcond_with test
%else
%bcond_without test
%endif
```

Right, that is the block in question. `bcond_with` and `bcond_without` actually act backwards to how everyone expects. So for Tumbleweed, `bcond_without` means it will default to building with tests. If that's the intended behaviour then we can just drop the python3-mock BuildRequires. If that isn't the intended behaviour, then let me know and I'll craft something.

**Comment by angelabriel** [comment]
I will drop the BuildRequires python3-mock with the next release of the package.
Thanks for your explanations and your patience.

**Comment by s-t-e-v-e-n-k** [comment]
This has been fixed for over 18 months, closing.
